language: java

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - sudo apt-get install jq
  - curl $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url) -o codacy-coverage-reporter-assembly.jar

before_cache:
  - rm -rf $HOME/.m2/repository/io/capdevila/gitlab/gitlab-cloner

after_success:
  - ./mvnw clean test jacoco:report coveralls:report -B
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r target/jacoco/jacoco.xml
