language: java

jdk:
  - oraclejdk8

script:
  - ./mvnw clean install -B --spring.profiles.active=test

sudo: false

cache:
  directories:
    - "$HOME/.m2"

before_cache:
  - rm -rf $HOME/.m2/repository/io/capdevila/gitlab/gitlab-cloner

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
