language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

#script:
#  - ./mvnw clean install -B

before_cache:
  - rm -rf $HOME/.m2/repository/io/capdevila/gitlab/gitlab-cloner

after_success:
  - ./mvnw clean test jacoco:report coveralls:report -B
